# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BHpjo2RCh21g5YM2ihKBugmMUw_0zHpI
"""


# Import necessary libraries
import streamlit as st
from transformers import pipeline

# Initialize the Hugging Face model

classifier = pipeline('text-classification', model='michellejieli/emotion_text_classifier')

# Title of the web application
st.title('Text Classification with Hugging Face')

# User input
user_input = st.text_input("Enter a text:")

# Function to get predictions
def get_predictions(text):
    result = classifier(text)[0]
    return result

# Get and display predictions
if st.button('Classify'):
    if user_input:
        result = get_predictions(user_input)
        st.write(f"Label: {result['label']}, with score: {result['score']}")
    else:
        st.write("Please enter a text.")
